### ISSUE TITLE
GHA for testing

### ISSUE THREAD

**Issue by theghall** [cph/remotable#27]
We no longer use Travis CI.  One note, the Appraisal gem expects a `.travis.yml` even locally, so that will have to stick around.  Testing should be done with `bundle exec appraisal rake test`.   It  _looks_ like the `.travis.yml` file drove what gets tested. i.e. it looks like it would do this if it were run with Travis CI

rails 6.0 with ruby 2.7
rails 6.0 with ruby 3.0
rails 6.1 with ruby 2.7
rails 6.1 with ruby 3.0
rails edge with ruby 3.0, failure would not cause the CI testing to fail

Since the `.travis.yml` file wont be used with GHA, you may have to run it this way, though I'm not sure how to run it with each ruby version or what ruby version it would use:
bundle exec appraisal rails-6.0 rake test
bundle exec appraisal rails-6.1 rake test
bundle exec appraisal rails-edge rake test, failure would not prevent merging

**Comment by kobsy** [comment]
Done! ✅
